### ISSUE TITLE
Failed to capture utm_source

### ISSUE THREAD

**Issue by driskerr** [pvcousin/sql-scratch-capstone-turn-in#2]
https://github.com/pvcousin/sql-scratch-capstone-turn-in/blob/ea224748dad4b1e8b4a7bdd3c70ae0c5a259135f/SQL%20Project%20Paul%20Cousin/code.sql#L3-L4

We were also looking for the "the number of distinct sources". `utm_source` refers to the sites that the campaign appeared on like: "google", "nytimes" or "buzzfeed". I am afraid there's a chance you confused `page_name` with the `utm_source` we were seeking.

This could have been accomplished with
``` 
SELECT DISTINCT utm_campaign, 
       utm_source

**Comment by pvcousin** [comment]
That's too simplistic and no challenge at all. I looked at actual campaigns that attract a user to a website for the first time. I followed the user all the way through to the very end even if the purchase ended on what you call another 'campaign'. Did you see my Excel spreadsheet which summarizes the activity of the four campaigns? My total purchases for the four campaigns would equal the total purchases for your seven or eight campaigns.
