### ISSUE TITLE
Missing retargeting campaigns because of extra subquery/join

### ISSUE THREAD

**Issue by driskerr** [pvcousin/sql-scratch-capstone-turn-in#3]
https://github.com/pvcousin/sql-scratch-capstone-turn-in/blob/ea224748dad4b1e8b4a7bdd3c70ae0c5a259135f/SQL%20Project%20Paul%20Cousin/code.sql#L49-L50

By joining the last touch and first touch tables, you are eliminating the 4 campaigns that were used for retargeting (like `weekly-newsletter` campaign from the email source or `paid-search` campaign from google). We were expecting you to join the `last_touch` table with `page_visits`, so you could appreciate the impact of all the adds on the last touch.

Props on using two subqueries though! Some complicated stuff you're running!

**Comment by pvcousin** [comment]
'So I could appreciate the impact of all the adds on the last touch', what does that even mean? I looked at the four campaigns that brought users to the website for the first time. By following the user id, I was able to find out how many people actually bought t-shirts. My total t-shirt sales for the four campaigns will equal the total t-shirts sales for your seven or eight 'campaigns'.
