### ISSUE TITLE
Corrected query

### ISSUE THREAD

**Issue by driskerr** [pvcousin/sql-scratch-capstone-turn-in#4]
https://github.com/pvcousin/sql-scratch-capstone-turn-in/blob/ea224748dad4b1e8b4a7bdd3c70ae0c5a259135f/SQL%20Project%20Paul%20Cousin/code.sql#L36-L52

```
WITH last_touch AS 
        (SELECT user_id,
 	MAX(timestamp) AS last_touch_at
    FROM page_visits
    GROUP BY user_id)
 SELECT lt.user_id,
 	lt.last_touch_at,
        pv.utm_campaign,
        COUNT(*) AS last_touch
   FROM last_touch lt
   JOIN page_visits pv
 	ON lt.user_id = pv.user_id
        AND lt.last_touch_at = pv.timestamp
  GROUP BY pv.utm_campaign;

**Comment by pvcousin** [comment]
People in marketing are more concerned about people not methods. How and why do people react to certain things or certain situations. In this case, how do people react to my website and my products, hence, which people purchased t-shirts from the campaigns that brought them to the website (landing).
If they didn't purchase, why not. Website not easy to negotiate? T-shirts not to their liking? Follow the users not the 'campaigns'.
