### ISSUE TITLE
See what you missed

### ISSUE THREAD

**Issue by driskerr** [pvcousin/sql-scratch-capstone-turn-in#6]
https://github.com/pvcousin/sql-scratch-capstone-turn-in/blob/ea224748dad4b1e8b4a7bdd3c70ae0c5a259135f/SQL%20Project%20Paul%20Cousin/code.sql#L3-L7

try running this to see the other campaigns you missed,
```
SELECT DISTINCT utm_campaign, 
   utm_source,
FROM page_visits
GROUP BY utm_campaign;

**Comment by pvcousin** [comment]
I didn't miss any campaigns. What you people call campaigns are not campaigns. Campaigns draw people to your website.
