### ISSUE TITLE
An interesting methodology

### ISSUE THREAD

**Issue by driskerr** [pvcousin/sql-scratch-capstone-turn-in#7]
https://github.com/pvcousin/sql-scratch-capstone-turn-in/blob/ea224748dad4b1e8b4a7bdd3c70ae0c5a259135f/SQL%20Project%20Paul%20Cousin/code.sql#L86

An interesting way of capturing the user's journey through the website. However, my same comment applies here - you are missing half the campaigns issued by CoolTShirt by joining with first_touch in this manner.

**Comment by pvcousin** [comment]
This method follows the user from landing to last touch, either to shopping, check out, or purchase. Which users that started in landing actually made a purchase? Who cares if they completed it on their first visit. Did they eventually make a purchase. If so, what campaign brought them to the website initially?
