### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by driskerr** [pvcousin/sql-scratch-capstone-turn-in#8]
## Rubric Score
 
### Criteria 1: Report
* _Score Level:_  3 (Meets Expectations)
* _Comment(s):_ Your slides are present a sufficient amount of information. However, the design of your slides leaves much to be desired. First and foremost, I recommend presenting data by inserting tables (like so:

|header 1| header 2| header 3|
|---|---|---|
data| data| you get the idea |
more data|

) it makes your data more readable and digestible to a client or outside audience. That being said, your text was very thorough at explaining your reasoning and thought-process.
 
### Criteria 2: Query Accuracy
* _Score Level:_ 1 (Does Not Meet Expectations)
* _Comment(s):_ You fail to capture the data necessary for the analysis. By focusing on the page and always inner joining with last_touch with first_touch, you failed to examine 4 of CoolTShirts campaigns, which happened to be retargeting campaigns that brought the user to the Check Out page or later.
 
### Criteria 3: Query Formatting
* _Score Level:_ 4 (Exceeds Expectations)
* _Comment(s):_ Queries adhere to at the rules of the [style guide](https://s3.amazonaws.com/codecademy-content/programs/learn-sql-from-scratch/SQL+Style+Guide+for+Learn+SQL+from+Scratch.pdf). Good work using aliases to rename the columns and using indentation to organize your subqueries, both make your queries more readable!
 
### Criteria 4: Understanding underlying concepts and terminology
* _Score Level:_ 3 (Meets Expectations)
* _Comment(s):_ You provided good explanations and interpretations of the data points' relevance to the CoolTShirts' actual business. I appreciate that you brought in outside knowledge like the average price of a T-shirts to calculate their monthly revenue. However, I think you miss understand the distinction between the first touch and the last touch. Because of you're incomplete queries, there are *exactly* equal numbers of the first and last touch attributions. This would mean that *every* customer who the visited the site visited once and only once and never returned. You'll see that retargeting campaigns of visitors who originally visited the site without purchasing brings in a substantial portion of CoolTShirts' transactions. Saying "Same as the first touch data. Good way to verify the data is correct" is a faulty assumption for the reasons I have outlined.

 ### Overall Score: 11/16
Your final question: "Why should CoolTShirts choose five campaigns when they only have four to begin with?" is very telling. Unfortunately, you failed to capture the full 8 campaigns that CoolTShirts runs, which hindered your understanding of touch-attribute-models, funnels, and the business problem. That being said, you have a knack for SQL queries as all your queries were well-written with aliases and indentation and were executable.

**Comment by pvcousin** [comment]
There are only four campaigns. A campaign is a marketing tool to draw people to a website for the first time. The other three are, therefor, not campaigns. A user could start a transaction, sign off, and then complete the transaction on another day. My queries followed users through the process by using 'user id' instead of looking at the 'seven' campaigns. This makes more sense since three of the 'campaigns' are not campaigns. As far as last touch, I don't recall the directions specifying what exactly a last touch is.
